### ISSUE TITLE
Qrcode in windows

### ISSUE THREAD

**Issue by indragunawan82** [vasani-arpit/WBOT#153] opened 2020-08-08 09:23 UTC
![image](https://user-images.githubusercontent.com/9045625/89706818-52c0ac00-d993-11ea-9cf2-45dcc3951bf7.png)

In windows, my qrcode become like attached. what is the solution for this?

**Comment by indragunawan82** [comment] 2020-08-08 15:41
Fyi .. i use nodemon

if i use node index.js 

it will work

**Comment by prakhargurunani** [comment] 2020-10-09 07:20
@indragunawan82 Does it work in powershell ?

**Comment by indragunawan82** [comment] 2020-10-09 08:00
i havent try in powershell, my goal is on linux

**Comment by prakhargurunani** [comment] 2020-10-09 08:44
@indragunawan82 It seems there is an issue with `nodemon` and it is just displaying raw QR code data. When you start a fresh server instance for first time with nodemon...does it work correctly ?

**Comment by indragunawan82** [comment] 2020-10-09 10:48
not working also

not only nodemon, if i run node src/index.js also gives error

if i got that error, then it will always error

Thanks
IG

**Comment by vasani-arpit** [comment] 2020-10-21 17:22
This must be mixup due to font or something. I have windows and I am not facing this issue. Please provide more details to reproduce. closing until we receive further info.

**Closed by vasani-arpit** 2020-10-21 17:22 UTC
Labels: bug, wontfix
