### ISSUE TITLE
WAPI didnt work since 27th Sept

### ISSUE THREAD

**Issue by noxxue** [vasani-arpit/WBOT#55] opened 2019-09-28 12:53 UTC
I think whatsapp change their API WAPI.js cant get login status and new messages come

**Comment by vasani-arpit** [comment] 2019-09-28 13:23
Yep. working on a fix.

**Comment by vasani-arpit** [comment] 2019-09-28 16:06
A fix is in place in [webhook branch](https://github.com/vasani-arpit/WBOT/tree/features/webhooks). Planning to merge it with master tomorrow.

**Comment by jrrcdev** [comment] 2019-09-29 01:46
The issue is when do you load the wapi code, using your workaround to wait until the laptop icon show up and than load the wapi code fix it.

**Comment by noxxue** [comment] 2019-09-29 06:17
solved thank you so much..

**Comment by andersondeoliveiramachado** [comment] 2019-10-01 20:37
https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/716

https://raw.githubusercontent.com/gfaraj/super-bot/982dd8e9290376cba286375c8e3b299c79e0ac16/clients/whatsapp/src/web/wapi.js

**Comment by vasani-arpit** [comment] 2019-10-02 06:31
@andersondeoliveiramachado 

Thanks,

Yes. I have added that solution and it is in webhook branch. I will merge it with master after I run a few tests.

**Closed** 2019-10-02 12:03 UTC
